sudo: false
language: node_js
node_js:
  - '8'
  - '10'
install:
  - npm i npminstall && npminstall
services:
  - mongodb
before_script:
  - sleep 15
script:
  - npm test
after_script:
  - npminstall codecov && codecov
